/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC721Bridgeable,
  IERC721BridgeableInterface,
} from "../IERC721Bridgeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "mintFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC721Bridgeable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721BridgeableInterface {
    return new utils.Interface(_abi) as IERC721BridgeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721Bridgeable {
    return new Contract(address, _abi, signerOrProvider) as IERC721Bridgeable;
  }
}
