/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMXBridgeableERC20,
  IMXBridgeableERC20Interface,
} from "../IMXBridgeableERC20";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ERC20Bridged",
    type: "event",
  },
  {
    inputs: [],
    name: "imxBridgeAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mintFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMXBridgeableERC20__factory {
  static readonly abi = _abi;
  static createInterface(): IMXBridgeableERC20Interface {
    return new utils.Interface(_abi) as IMXBridgeableERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMXBridgeableERC20 {
    return new Contract(address, _abi, signerOrProvider) as IMXBridgeableERC20;
  }
}
